# Change these first
owner: LACMTA # Your GitHub organization or username, where this repository lives
repo: art-bus-uptime # The name of this repository

sites:
  - name: Overall Art Bus status
    url: https://lacmta.github.io/metro-art-bus-tracker/status-data/
    __dangerous__body_down: '"summary":{"status":"no trips"}'
    __dangerous__body_degraded: '"summary":{"status":"some buses running"}'
  - name: Metro Art Bus No. 1
    url: https://lacmta.github.io/metro-art-bus-tracker/status-data/
    __dangerous__body_down: '"4111":{"status":"no trips"}'
  - name: Metro Art Bus No. 2
    url: https://lacmta.github.io/metro-art-bus-tracker/status-data/
    __dangerous__body_down: '"5621":{"status":"no trips"}'
  - name: Metro Art Bus No. 3
    url: https://lacmta.github.io/metro-art-bus-tracker/status-data/
    __dangerous__body_down: '"3944":{"status":"no trips"}'


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /art-bus-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Art Bus Uptime
  introTitle: "Checks to see if there are any Art Buses running"
  introMessage: If all the art buses are running you will see "Status OK". "Degraded" status means some art buses are running. "Down" means that no art buses are running.  
  navbar:
    - title: Status
      href: /art-bus-uptime
    - title: GitHub
      href: https://github.com/LACMTA/art-bus-uptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
